#!/bin/bash
if [[ ! -f /etc/crontabsum ]];then
    cat /etc/crontab | md5sum > crontabsum
    sudo mv crontabsum /etc/crontabsum
    exit
fi

old=`cat /etc/crontabsum`
new=`cat /etc/crontab | md5sum`

if [[ $old != $new ]]; then
    echo $new > /etc/crontabsum
    echo "Hey, there is something going on here!" |  mail -s "The crontab has been modified" root
fi

chmod 755 04
sudo cp 04 /etc/cron.daily/check_crontab.sh
echo "0 0 * * * root /etc/cron.daily/check_crontab.sh" | crontab
crontab -l
