################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../libft/ft_atoi.c \
../libft/ft_bzero.c \
../libft/ft_isalnum.c \
../libft/ft_isalpha.c \
../libft/ft_isascii.c \
../libft/ft_isdigit.c \
../libft/ft_isprint.c \
../libft/ft_itoa.c \
../libft/ft_list_reverse.c \
../libft/ft_lstadd.c \
../libft/ft_lstdel.c \
../libft/ft_lstdelone.c \
../libft/ft_lstiter.c \
../libft/ft_lstmap.c \
../libft/ft_lstnew.c \
../libft/ft_map.c \
../libft/ft_memalloc.c \
../libft/ft_memccpy.c \
../libft/ft_memchr.c \
../libft/ft_memcmp.c \
../libft/ft_memcpy.c \
../libft/ft_memdel.c \
../libft/ft_memmove.c \
../libft/ft_memset.c \
../libft/ft_putchar.c \
../libft/ft_putchar_fd.c \
../libft/ft_putendl.c \
../libft/ft_putendl_fd.c \
../libft/ft_putnbr.c \
../libft/ft_putnbr_fd.c \
../libft/ft_putstr.c \
../libft/ft_putstr_fd.c \
../libft/ft_strcapitalize.c \
../libft/ft_strcat.c \
../libft/ft_strchr.c \
../libft/ft_strclr.c \
../libft/ft_strcmp.c \
../libft/ft_strcpy.c \
../libft/ft_strdel.c \
../libft/ft_strdup.c \
../libft/ft_strequ.c \
../libft/ft_striter.c \
../libft/ft_striteri.c \
../libft/ft_strjoin.c \
../libft/ft_strlcat.c \
../libft/ft_strlen.c \
../libft/ft_strlowcase.c \
../libft/ft_strmap.c \
../libft/ft_strmapi.c \
../libft/ft_strncat.c \
../libft/ft_strncmp.c \
../libft/ft_strncpy.c \
../libft/ft_strnequ.c \
../libft/ft_strnew.c \
../libft/ft_strnstr.c \
../libft/ft_strrchr.c \
../libft/ft_strsplit.c \
../libft/ft_strstr.c \
../libft/ft_strsub.c \
../libft/ft_strtrim.c \
../libft/ft_strupcase.c \
../libft/ft_tolower.c \
../libft/ft_toupper.c \
../libft/get_next_line.c 

O_SRCS += \
../libft/ft_atoi.o \
../libft/ft_bzero.o \
../libft/ft_isalnum.o \
../libft/ft_isalpha.o \
../libft/ft_isascii.o \
../libft/ft_isdigit.o \
../libft/ft_isprint.o \
../libft/ft_itoa.o \
../libft/ft_list_reverse.o \
../libft/ft_lstadd.o \
../libft/ft_lstdel.o \
../libft/ft_lstdelone.o \
../libft/ft_lstiter.o \
../libft/ft_lstmap.o \
../libft/ft_lstnew.o \
../libft/ft_map.o \
../libft/ft_memalloc.o \
../libft/ft_memccpy.o \
../libft/ft_memchr.o \
../libft/ft_memcmp.o \
../libft/ft_memcpy.o \
../libft/ft_memdel.o \
../libft/ft_memmove.o \
../libft/ft_memset.o \
../libft/ft_putchar.o \
../libft/ft_putchar_fd.o \
../libft/ft_putendl.o \
../libft/ft_putendl_fd.o \
../libft/ft_putnbr.o \
../libft/ft_putnbr_fd.o \
../libft/ft_putstr.o \
../libft/ft_putstr_fd.o \
../libft/ft_strcapitalize.o \
../libft/ft_strcat.o \
../libft/ft_strchr.o \
../libft/ft_strclr.o \
../libft/ft_strcmp.o \
../libft/ft_strcpy.o \
../libft/ft_strdel.o \
../libft/ft_strdup.o \
../libft/ft_strequ.o \
../libft/ft_striter.o \
../libft/ft_striteri.o \
../libft/ft_strjoin.o \
../libft/ft_strlcat.o \
../libft/ft_strlen.o \
../libft/ft_strlowcase.o \
../libft/ft_strmap.o \
../libft/ft_strmapi.o \
../libft/ft_strncat.o \
../libft/ft_strncmp.o \
../libft/ft_strncpy.o \
../libft/ft_strnequ.o \
../libft/ft_strnew.o \
../libft/ft_strnstr.o \
../libft/ft_strrchr.o \
../libft/ft_strsplit.o \
../libft/ft_strstr.o \
../libft/ft_strsub.o \
../libft/ft_strtrim.o \
../libft/ft_strupcase.o \
../libft/ft_tolower.o \
../libft/ft_toupper.o \
../libft/get_next_line.o 

OBJS += \
./libft/ft_atoi.o \
./libft/ft_bzero.o \
./libft/ft_isalnum.o \
./libft/ft_isalpha.o \
./libft/ft_isascii.o \
./libft/ft_isdigit.o \
./libft/ft_isprint.o \
./libft/ft_itoa.o \
./libft/ft_list_reverse.o \
./libft/ft_lstadd.o \
./libft/ft_lstdel.o \
./libft/ft_lstdelone.o \
./libft/ft_lstiter.o \
./libft/ft_lstmap.o \
./libft/ft_lstnew.o \
./libft/ft_map.o \
./libft/ft_memalloc.o \
./libft/ft_memccpy.o \
./libft/ft_memchr.o \
./libft/ft_memcmp.o \
./libft/ft_memcpy.o \
./libft/ft_memdel.o \
./libft/ft_memmove.o \
./libft/ft_memset.o \
./libft/ft_putchar.o \
./libft/ft_putchar_fd.o \
./libft/ft_putendl.o \
./libft/ft_putendl_fd.o \
./libft/ft_putnbr.o \
./libft/ft_putnbr_fd.o \
./libft/ft_putstr.o \
./libft/ft_putstr_fd.o \
./libft/ft_strcapitalize.o \
./libft/ft_strcat.o \
./libft/ft_strchr.o \
./libft/ft_strclr.o \
./libft/ft_strcmp.o \
./libft/ft_strcpy.o \
./libft/ft_strdel.o \
./libft/ft_strdup.o \
./libft/ft_strequ.o \
./libft/ft_striter.o \
./libft/ft_striteri.o \
./libft/ft_strjoin.o \
./libft/ft_strlcat.o \
./libft/ft_strlen.o \
./libft/ft_strlowcase.o \
./libft/ft_strmap.o \
./libft/ft_strmapi.o \
./libft/ft_strncat.o \
./libft/ft_strncmp.o \
./libft/ft_strncpy.o \
./libft/ft_strnequ.o \
./libft/ft_strnew.o \
./libft/ft_strnstr.o \
./libft/ft_strrchr.o \
./libft/ft_strsplit.o \
./libft/ft_strstr.o \
./libft/ft_strsub.o \
./libft/ft_strtrim.o \
./libft/ft_strupcase.o \
./libft/ft_tolower.o \
./libft/ft_toupper.o \
./libft/get_next_line.o 

C_DEPS += \
./libft/ft_atoi.d \
./libft/ft_bzero.d \
./libft/ft_isalnum.d \
./libft/ft_isalpha.d \
./libft/ft_isascii.d \
./libft/ft_isdigit.d \
./libft/ft_isprint.d \
./libft/ft_itoa.d \
./libft/ft_list_reverse.d \
./libft/ft_lstadd.d \
./libft/ft_lstdel.d \
./libft/ft_lstdelone.d \
./libft/ft_lstiter.d \
./libft/ft_lstmap.d \
./libft/ft_lstnew.d \
./libft/ft_map.d \
./libft/ft_memalloc.d \
./libft/ft_memccpy.d \
./libft/ft_memchr.d \
./libft/ft_memcmp.d \
./libft/ft_memcpy.d \
./libft/ft_memdel.d \
./libft/ft_memmove.d \
./libft/ft_memset.d \
./libft/ft_putchar.d \
./libft/ft_putchar_fd.d \
./libft/ft_putendl.d \
./libft/ft_putendl_fd.d \
./libft/ft_putnbr.d \
./libft/ft_putnbr_fd.d \
./libft/ft_putstr.d \
./libft/ft_putstr_fd.d \
./libft/ft_strcapitalize.d \
./libft/ft_strcat.d \
./libft/ft_strchr.d \
./libft/ft_strclr.d \
./libft/ft_strcmp.d \
./libft/ft_strcpy.d \
./libft/ft_strdel.d \
./libft/ft_strdup.d \
./libft/ft_strequ.d \
./libft/ft_striter.d \
./libft/ft_striteri.d \
./libft/ft_strjoin.d \
./libft/ft_strlcat.d \
./libft/ft_strlen.d \
./libft/ft_strlowcase.d \
./libft/ft_strmap.d \
./libft/ft_strmapi.d \
./libft/ft_strncat.d \
./libft/ft_strncmp.d \
./libft/ft_strncpy.d \
./libft/ft_strnequ.d \
./libft/ft_strnew.d \
./libft/ft_strnstr.d \
./libft/ft_strrchr.d \
./libft/ft_strsplit.d \
./libft/ft_strstr.d \
./libft/ft_strsub.d \
./libft/ft_strtrim.d \
./libft/ft_strupcase.d \
./libft/ft_tolower.d \
./libft/ft_toupper.d \
./libft/get_next_line.d 


# Each subdirectory must supply rules for building sources it contributes
libft/%.o: ../libft/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


